apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-plus.fullname" . }}-secret
  labels:
    {{- include "jenkins-plus.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.user | quote }}
  admin-password: {{ .Values.admin.password | quote }}
  {{- if .Values.oidc.enabled }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.github.privateKey }}
  github-app-private-key: {{ .Values.github.privateKey | quote }}
  {{- end }}
  {{- if .Values.vault.enabled }}
  vault-role-id: {{ .Values.vault.roleId | quote }}
  vault-secret-id: {{ .Values.vault.secretId | quote }}
  {{- end }}
  {{- if .Values.slack.enabled }}
  slack-token: {{ .Values.slack.token | quote }}
  {{- end }}
  {{- if .Values.sonar.enabled }}
  sonar-token: {{ .Values.sonar.token | quote }}
  {{- end }}
